### ISSUE TITLE
Request a full single-stage network for the single stage training

### ISSUE THREAD

**Issue by xuhuazhe** [cvlab-epfl/single-stage-pose#2]
Dear authors,
Thank you so much for opensourcing your work!! I think if there is a full code to train the single-stage network, it would be very useful and impactful in many domains (vision, robotics, etc)!! 
Thank you!!

**Comment by YinlinHu** [comment]
@xuhuazhe , Thank you for your interest in our work. We do not plan to release the full code, as it's correspondence-extraction part is exactly the same as PVNet. Our paper is focused on inferring pose from correspondences, rather than correspondence extraction itself. And also, PVNet has already done a great job ... I think it will be easy for you to merge with it.

**Comment by YinlinHu** [comment]
@xuhuazhe , Thank you for your interest in our work. Sorry that we do not plan to release the full code due to some commercial reasons, also because it's correspondence-extraction part is exactly the same as PVNet. Our paper is focused on inferring pose from correspondences, rather than correspondence extraction itself. PVNet has already done a great job ... I think it will be easy for you to merge with it.

**Comment by xuhuazhe** [comment]
thank you for the reply! Closing the issue.
